### ISSUE TITLE
map_nt_to_emulator_protection

### ISSUE THREAD

**Issue by leftspace89** [momo5502/emulator#30]
https://github.com/momo5502/emulator/blob/main/src/windows-emulator/memory_utils.hpp#L38

I'm not sure if this was intended or bug but i had to change to this.

`case PAGE_EXECUTE_READWRITE:
	return memory_permission::all;
`

**Comment by momo5502** [comment]
uh, yeah, looks like i fucked up 😂 feel free to open up a PR :D

**Comment by leftspace89** [comment]
you got this :) also out ouf topic but is it possible to run dllmain with reserved arg. I'm more interested with emulating dll not just an executable. 

i don't see any code related which runs dllmain with correct args.

`
const auto main_thread_id = context.create_thread(emu, context.executable->entry_point, 0, 0);
switch_to_thread(*this, main_thread_id);
`

**Comment by momo5502** [comment]
> you got this :) also out ouf topic but is it possible to run dllmain with reserved arg. I'm more interested with emulating dll not just an executable.
> 
> i don't see any code related which runs dllmain with correct args.
> 
> `const auto main_thread_id = context.create_thread(emu, context.executable->entry_point, 0, 0); switch_to_thread(*this, main_thread_id);`

DllMain is never called explicitly from the emulator, because ntdll runs DllMain. There is a lot more involved than just calling it, e.g. you need to setup TLS.

This emulator only supports emulating entire processes. If you want to emulate a Dll, I recommend integrating it somewhere. You can e.g. use rundll32.exe, or build your own host application that just calls LoadLibrary and emulate that, which will eventually emulate your Dll

**Comment by momo5502** [comment]
Fixed: d83f2c61e8961259aa88078d8be6d90db2b4ed7b

**Comment by leftspace89** [comment]
can you do some sample for LoadLibrary, because when I try it just returns NULL and doesn't load any dll.
also tried LdrLoadDll it just simply doesn't load anything.


![image](https://github.com/user-attachments/assets/0288f877-d27b-4017-8c3b-ad5781e87e5e)

**Comment by momo5502** [comment]
Jep, loadlibrary seems to fail because of an unimplemented syscall. let me try to implement it.

**Comment by momo5502** [comment]
i implemented the syscall (which is probably not relevant for you as I'm running insider builds) and indeed, loadlibrary seems to do nothing. i'll investigate

**Comment by momo5502** [comment]
progress will no be tracked in #31

**Comment by momo5502** [comment]
load library is now fixed. see https://github.com/momo5502/emulator/issues/31
