### ISSUE TITLE
Double usage of parent_path() causes invalid working directory

### ISSUE THREAD

**Issue by Redcommander** [momo5502/emulator#34]
When attempting to run an application with a path of (for example) `C:\SomeApplication\Binaries\Win64\App.exe` the working directory will be set to `C:\SomeApplication\Binaries\` instead of the expected `C:\SomeApplication\Binaries\Win64\`. This causes DLL load attempts to occur in the wrong directory.

This seems to be due to the function `canonicalize_path` unexpectedly using `parent_path()` while `parent_path()` is already being called in `current_folder = canonicalize_path(settings.application).parent_path().wstring() + L"\\";` (in the function `setup_context` from `windows_emulator.cpp`).

Removing the `parent_path()` call from `canonicalize_path` function fixes the issue for me.

**Comment by momo5502** [comment]
Should be fixed now. Thanks for reporting. Next time feel free to create a pull request :D
