### ISSUE TITLE
Issue with Missing Directory for Registry Hive File

### ISSUE THREAD

**Issue by reddead-coder** [momo5502/emulator#37]
I encountered an issue while using the analyzer tool. Here's the command and output:

`PS E:\emulator\build\vs2022\artifacts-relwithdebinfo> .\analyzer.exe .\test-sample.exe
Bad hive file 'E:\emulator\build\vs2022\artifacts-relwithdebinfo\registry\SYSTEM': Failed to read file data`

The directory registry\SYSTEM does not exist at the specified location.

Could you please let me know how to resolve this issue? Should this directory be created manually, or is there something else I'm missing?

Thanks in advance!

**Comment by momo5502** [comment]
You need to create a registry dump using this script: https://github.com/momo5502/emulator/blob/main/src/grab-registry.bat

**Comment by reddead-coder** [comment]
that worked perfectly! Thank you so much for the quick and clear response.
